# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170719_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date',
            field=models.DateField(),
        ),
    ]
