# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170719_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='date',
        ),
    ]
