# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20170801_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='phone',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=120),
        ),
    ]
